name: 'StackProject'   # use the exact project name shown at top of dbt_project.yml
version: '1.0'
config-version: 2

models:
  StackProject:
    Silver_Layer:
      +schema: Silver_layer
      +materialized: view
    Gold_Layer:
      +schema: Gold_layer
      +materialized: table 
      Facts:
        +materialized: View
    Gold_facts:   
      +schema: Gold_Facts 
      +materialized: View
    Semantic_Layer:   
      +schema: Semantic_Layer 
      +materialized: view  

    

  


     
 

  


