name: 'StackProject'   # use the exact project name shown at top of dbt_project.yml
version: '1.0'
config-version: 2

models:
  StackProject:
    Silver_Layer:
      +schema: So_silver_layer
      +materialized: view
    Gold_Layer:
      +schema: So_Gold_layer
      +materialized: table
    Gold_facts:   
      +schema: So_Gold_Facts 
      +materialized: View
    Semantic_Layer:   
      +schema: So_Semantic_Layer 
      +materialized: view  

    

  


     
 

  


