name: 'StackProject'   # use the exact project name shown at top of dbt_project.yml
version: '1.0'
config-version: 2

models:
  StackProject:
    +schema: So_silver_layer      # <-- forces BigQuery dataset for all models
    +materialized: view
    Gold_Layer:
      +schema: So_Gold_layer      # <-- forces BigQuery dataset for all models
      +materialized: view
    Mart_Layer:
      +schema: So_Marts
      +materialized: view

  


